name: BriefCase Package Deployment
on:
    push:
        branches:
            - main
            - feature/**
jobs:
    build-windows:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v4
            
      - name: Setup Python 3.11.9
        uses:  actions/setup-python@v3
        with:
         python-version: '3.11.9'
            
      - name: Activate virtual environment and install dependencies
        run: | 
         python -m venv .venv
         .venv\Scripts\activate.bat
         python -m pip install -r requirements.txt
      