name: BriefCase Package Deployment
on:
    push:
        branches:
            - main
            - feature/**
jobs:
    build-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout
            
            - name: Setup Python 3.11.9
              uses:  actions/setup-python
              with:
                python-version: '3.11.9'
            
            - name: List Contents
              run: | 
                ls -la