name: Training Model

on:
  push:
      branches:
        - Jasons_Research
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Set up Virtual Environment
        run: |
          python -m venv .venv
          source .venv/Scripts/activate
          pip install -r requirements.txt

